config/routes.rb
Osem::Application.routes.draw do

  get 'conference/show'

  devise_for :users, :controllers => { :registrations => :registrations }, :path => 'accounts'

  namespace :admin do
    resources :users
    resources :people
    resources :conference do
      get "/schedule" => "schedule#show"
      patch "/schedule" => "schedule#update"
      get "/stats" => "stats#index"
      get "/venue" => "venue#show", :as => "venue_info"
      patch "/venue" => "venue#update", :as => "venue_update"
      get "/dietary_choices" => "dietchoices#show", :as => "dietary_list"
      patch "/dietary_choices" => "dietchoices#update", :as => "dietary_update"
      get "/volunteers_list" => "volunteers#show"
      get "/volunteers" => "volunteers#index", :as => "volunteers_info"
      patch "/volunteers" => "volunteers#update", :as => "volunteers_update"

      patch '/registrations/change_field' => 'registrations#change_field'
      resources :registrations

      resources :difficulty_levels, only: [:show, :update, :index]

      resources :rooms, only: [:show, :update, :index]

      resources :tracks, only: [:show, :update, :index]

      resources :eventtypes, only: [:show, :index] do
        collection do
          patch :update
        end
      end

      resources :social_events, only: [:show, :update, :index]

      resources :supporter_levels, only: [:show, :update, :index]

      resources :emails, only: [:show, :update, :index]

      resources :callforpapers, only: [:create] do
        collection do
          patch :update
          get :show
        end
      end

      patch "/questions/update_conference" => "questions#update_conference"
      resources :questions

      resources :events do
        member do
          post :comment
          patch :accept
          patch :confirm
          patch :cancel
          patch :reject
          patch :unconfirm
          patch :restart
          get :vote
        end
        resource :speaker, :only => [:edit, :update]
      end

      resources :supporters
    end
  end

  resources :conference, only: [:show] do
    resources :proposal do
      resources :event_attachment, :controller => "event_attachments"
      patch '/confirm' => 'proposal#confirm'
      patch '/restart' => 'proposal#restart'
    end
    resource :schedule, :only => [] do
      get "/" => "schedule#index"
    end
    member do
      get "/register" => "conference_registration#register"
      patch "/register" => "conference_registration#update"
      delete "/register" => "conference_registration#unregister"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, :only => :index do
        resources :conferences, :only => :index
        resources :rooms, :only => :index
        resources :tracks, :only => :index
        resources :speakers, :only => :index
        resources :events, :only => :index
      end
      resources :rooms, :only => :index
      resources :tracks, :only => :index
      resources :speakers, :only => :index
      resources :events, :only => :index
    end
  end

  get "/admin" => redirect("/admin/conference")

  root :to => "home#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  include ActiveRecord::Transitions
  has_paper_trail
  attr_accessible :title, :subtitle, :abstract, :description, :event_type_id, :people_attributes, :person, :proposal_additional_speakers, :track_id, :media_id, :media_type, :require_registration, :difficulty_level_id

  acts_as_commentable

  has_many :event_people, :dependent => :destroy
  has_many :event_attachments, :dependent => :destroy
  has_many :people, :through => :event_people
  has_many :speakers, :through => :event_people, :source => :person
  has_many :votes
  has_many :voters, :through => :votes, :source => :person
  belongs_to :event_type

  has_and_belongs_to_many :registrations

  belongs_to :track
  belongs_to :room
  belongs_to :difficulty_level
  belongs_to :conference

  accepts_nested_attributes_for :event_people, :allow_destroy => true
  accepts_nested_attributes_for :event_attachments, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :people
  before_create :generate_guid

  validate :abstract_limit
  validate :biography_exists
  validates :title, :presence => true
  validates :abstract, :presence => true
  validates :media_type, :allow_nil => true, inclusion: {in: Conference.media_types.values}

  scope :confirmed, -> { where(state: 'confirmed') }

  state_machine :initial => :new do
    state :new
    state :withdrawn
    state :unconfirmed
    state :confirmed
    state :canceled
    state :rejected

    event :restart do
      transitions to: :new, from: [:rejected, :withdrawn, :canceled]
    end
    event :withdraw do
      transitions to: :withdrawn, from: [:new, :unconfirmed, :confirmed]
    end
    event :accept do
      transitions to: :unconfirmed, from: [:new], on_transition: :process_acceptance
    end
    event :confirm do
      transitions to: :confirmed, from: :unconfirmed, on_transition: :process_confirmation
    end
    event :cancel do
      transitions to: :canceled, from: [:unconfirmed, :confirmed]
    end
    event :reject do
      transitions to: :rejected, from: [:new], on_transition: :process_rejection
    end
  end

  def voted?(event, person)
    event.votes.where("person_id = ?", person).first
  end
  
  def average_rating
    @total_rating = 0
    self.votes.each do |vote|
      @total_rating = @total_rating + vote.rating
    end
    @total = self.votes.size
    number_with_precision(@total_rating / @total.to_f, :precision => 2, :strip_insignificant_zeros => true)
  end

  def submitter
    result = self.event_people.where(:event_role => "submitter").first
    if !result.nil?
      result.person
    else
      person = nil
      # Perhaps the event_people haven't been saved, if this is a new proposal
      self.event_people.each do |p|
        if p.event_role == "submitter"
          person = p.person
        end
      end
      person
    end
  end

  def as_json(options)
    json = super(options)

    if self.room.nil?
      json[:room_guid] = nil
    else
      json[:room_guid] = self.room.guid
    end

    if self.track.nil?
      json[:track_color]  = "#ffffff"
    else
      json[:track_color] = self.track.color;
    end

    if self.event_type.nil?
      json[:length] = 25
    else
      json[:length] = self.event_type.length
    end

    json
  end

  def transition_possible?(transition)
    self.class.state_machine.events_for(self.current_state).include?(transition)
  end

  def process_confirmation
    if self.conference.email_settings.send_on_confirmed_without_registration?
      if self.conference.registrations.where(:person_id => self.submitter.id).first.nil?
        Mailbot.confirm_reminder_mail(self).deliver
      end
    end
  end

  def process_acceptance(options)
    if conference.email_settings.send_on_accepted &&
        options[:send_mail].blank?
      Rails.logger.debug 'Sending event acceptance mail'
      Mailbot.acceptance_mail(self).deliver
    end
  end

  def process_rejection(options)
    if conference.email_settings.send_on_rejected &&
        options[:send_mail].blank?
      Rails.logger.debug 'Sending rejected mail'
      Mailbot.rejection_mail(self).deliver
    end
  end

  def abstract_word_count
    if self.abstract.nil?
      0
    else
      self.abstract.split.size
    end
  end

  def week
    created_at.strftime('%W').to_i
  end

  private

  def abstract_limit
    len = self.abstract.split.size
    max = self.event_type.maximum_abstract_length
    min = self.event_type.minimum_abstract_length

    if len < min
      errors.add(:abstract, "cannot have less than #{min} words")
    end

    if len > max
      errors.add(:abstract, "cannot have more than #{max} words")
    end
  end

  def biography_exists
    if self.submitter.biography_word_count == 0
      errors.add(:person_biography, "must be filled out")
    end
  end

  def generate_guid
    begin
      guid = SecureRandom.urlsafe_base64
    end while self.class.where(:guid => guid).exists?
    self.guid = guid
  end

end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  attr_accessible :title, :length, :minimum_abstract_length, :maximum_abstract_length

  belongs_to :conference

  validates :length, :numericality => {:greater_than => 0} 

  alias_attribute :name, :title
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_filter :verify_organizer

  # FIXME: The timezome should only be applied on output, otherwise
  # you get lost in timezone conversions...
  # around_filter :set_timezone_for_this_request

  def set_timezone_for_this_request(&block)
    Time.use_zone(@conference.timezone, &block)
  end

  def index
    @events = @conference.events
    @tracks = @conference.tracks
    @machine_states = @events.state_machine.states.map
    @event_types = @conference.event_types

    @mystates = []
    @mytypes = []
    @eventstats = Hash.new
    statelength = 0
    @totallength = 0

    @machine_states.each do |mystate|
      length = 0
      events_mystate= @events.where("state" => mystate.name)
      if events_mystate.count > 0
        @mystates << mystate
        events_mystate.each do |myevent|
          length += myevent.event_type.length
        end
        @eventstats["#{mystate.name}"] = {"count" => events_mystate.count, "length" => length}
      end
    end
    
    @event_types.each do |mytype|
      events_mytype = @events.where("event_type_id" => mytype.id)
      if events_mytype.count > 0
        @mytypes << mytype
      end
    end
    @mytypes.each do |mytype|
      @mystates.each do |mystate|
        events_mytype = @events.where("event_type_id" => mytype.id)
        events_mytype_mystate= events_mytype.where("state" => mystate.name)
        typelength = 0
        if events_mytype_mystate.count > 0
          events_mytype_mystate.each do |myevent|
            typelength += myevent.event_type.length
            @totallength += myevent.event_type.length
          end
          @eventstats[mytype.title] = {"count" => events_mytype.count, "length" => events_mytype.count * mytype.length} if @eventstats[mytype.title] == nil
          tmp = {"#{mystate.name}" => {"type_state_count" => events_mytype_mystate.count,  "type_state_length" => typelength}}
          @eventstats[mytype.title].merge!(tmp)
        end
      end
    end
    @eventstats["totallength"] = @totallength

    respond_to do |format|
      format.html
      # Explicity call #to_json to avoid the use of EventSerializer
      format.json { render :json => Event.where(:state => :confirmed).to_json }
    end
  end

  def show
    @event = @conference.events.find(params[:id])
    @tracks = @conference.tracks
    @event_types = @conference.event_types
    @comments = @event.root_comments
    @comment_count = @event.comment_threads.count
    @ratings = @event.votes.includes(:person)
    @difficulty_levels = @conference.difficulty_levels
  end

  def edit
    @event = @conference.events.find(params[:id])
    @event_types = @conference.event_types
    @tracks = Track.all
    @comments = @event.root_comments
    @comment_count = @event.comment_threads.count
    @person = @event.submitter
    @url = admin_conference_event_path(@conference.short_title, @event)
  end

  def comment
    event = @conference.events.find_by_id(params[:id])
    comment = Comment.build_from(event, current_user.id, params[:comment])
    comment.save!
    if !params[:parent].nil?
      comment.move_to_child_of(params[:parent])
    end

    redirect_to admin_conference_event_path(:conference_id => @conference.short_title)
  end

  def update
    @event = Event.find(params[:id])
    if params.has_key? :track_id
      @event.update_attribute(:track_id, params[:track_id])
    end
    if params.has_key? :event_type_id
      @event.update_attribute(:event_type_id, params[:event_type_id])
    end
    if params.has_key? :difficulty_level_id
      @event.update_attribute(:difficulty_level_id, params[:difficulty_level_id])
    end

    if @event.submitter.update_attributes!(params[:person]) && @event.update_attributes!(params[:event])
      flash[:notice] = "Successfully updated #{@event.title}."
    else
      flash[:notice] = "Update not successful."
    end
    
    redirect_back_or_to(admin_conference_event_path(@conference.short_title, @event))
  end

  def create
  end

  def accept
    update_state(params[:id], :accept, 'Event accepted!', true)
  end

  def confirm
    update_state(params[:id], :confirm, 'Event confirmed!')
  end

  def cancel
    update_state(params[:id], :cancel, 'Event canceled!')
  end

  def reject
    update_state(params[:id], :reject, 'Event rejected!', true)
  end

  def restart
    update_state(params[:id], :restart, 'Review started!')
  end

  def vote
    @event = Event.find(params[:id])
    @ratings = @event.votes.includes(:person)
    
    if votes = current_user.person.votes.find_by_event_id(params[:id])
      votes.update_attributes(:rating => params[:rating])
    else
      @myvote = @event.votes.build
      @myvote.person = current_user.person
      @myvote.rating = params[:rating]
      @myvote.save
    end

    respond_to do |format|
      format.html { redirect_to admin_conference_event_path(@conference.short_title, @event)}
      format.js
    end
  end

  private

  def update_state(id, transition, notice, mail = false)
    event = Event.find(id)
    if mail
      check_mail_settings
    end
    if event
      begin
        if mail
          event.send(transition,
                     send_mail: params[:send_mail])
        else
          event.send(transition)
        end
        event.save
      rescue Transitions::InvalidTransition => e
        redirect_to(
            admin_conference_events_path(conference_id: @conference.short_title),
            notice: "Update state failed. #{e.message}") && return
      end
      redirect_to(admin_conference_events_path(conference_id: @conference.short_title),
                  notice: notice)
    else
      redirect_to(admin_conference_events_path(conference_id: @conference.short_title),
                  notice: 'Error! Could not find event!')
    end
  end

  def check_mail_settings
    if !params[:send_mail].blank? && event &&
        event.conference.email_settings.rejected_email_template.nil? &&
        event.conference.email_settings.accepted_email_template.nil?
      redirect_to(admin_conference_events_path(conference_id: @conference.short_title),
                  notice: 'Update Email Template before Sending Mails') && return
    end
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::BaseController
  respond_to :json

  def index
    events = Event.includes(:conference, :track, :room, :event_type, {:event_people => :person})
    unless params[:conference_id].blank?
      events = events.where("conferences.guid" => params[:conference_id])
    end
    respond_with events.confirmed
  end
end

app/views/admin/events/_person_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :email
    = f.input :public_name
  = remove_association_link :person, f

app/views/admin/events/_proposal.html.haml
.row
  .col-md-12
    %h3
      = @event.title
      %br
      %small
        = @event.subtitle
      = link_to "Edit", edit_admin_conference_event_path(@conference.short_title, @event), :class => "btn btn-mini btn-default pull-right"

.row
  .col-md-12
    %table.table
      %tr
        %td{:style => "width:15%"}
          %b Type
        %td
          .dropdown
            = link_to "#", :class => "dropdown-toggle", :id => "type-dropdown" do
              - if @event.event_type.nil?
                Event Type
              - else
                = @event.event_type.title
              <b class="caret"></b>
            %ul.dropdown-menu
              - @event_types.each do |type|
                %li= link_to type.title, admin_conference_event_path(@conference.short_title, @event, :event_type_id => type.id) ,
                  :method => :put, :event_type_id => type.id
      %tr
        %td
          %b State
        %td
          .dropdown
            = link_to "#", :class => "dropdown-toggle" do
              = @event.state.humanize
              <b class="caret"></b>
            %ul.dropdown-menu
              - if @event.transition_possible? :accept
                %li= link_to "Accept event (no email)", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :accept, :send_mail => false),
                    :method => :put, :hint => "Accept this event without sending an automated email."
                %li= link_to "Accept event (WITH email)", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :accept, :send_mail => true),
                    :method => :put, :hint => "Accept this event and send an automated email."
              - if @event.transition_possible? :reject
                %li= link_to "Reject event (no email)", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :reject, :send_mail => false),
                    :method => :put, :confirm => "Are you sure?",
                    :hint => "Reject this event without sending an automated email."
                %li= link_to "Reject event (WITH email)", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :reject, :send_mail => true),
                    :method => :put, :confirm => "Are you sure?",
                    :hint => "Reject this event and send an automated email."
              - if @event.transition_possible? :start_review
                %li= link_to "Start review", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :start_review),
                    :method => :put
              - if @event.transition_possible? :confirm
                %li= link_to "Confirm event", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :confirm),
                            :method => :put, :hint => "Confirm that the speaker(s) will be present and that the event will actually take place."
              - if @event.transition_possible? :cancel
                %li= link_to "Cancel event", update_state_admin_conference_event_path(@conference.short_title, @event, :transition => :cancel),
                  :method => :put, :hint => "Mark this event as cancelled. Usually this means that the speakers had to cancel their appearance."
      %tr
        %td
          %b Track
        %td
          .dropdown
            = link_to "#", :class => "dropdown-toggle", :id => "track-dropdown" do
              - if @event.track.nil?
                Track
              - else
                = @event.track.name
              <b class="caret"></b>
            %ul.dropdown-menu
              - @tracks.each do |track|
                %li= link_to track.name, admin_conference_event_path(@conference.short_title, @event, :track_id => track.id) ,
                  :method => :put, :track_id => track.id
      %tr
        %td
          %b Difficulty
        %td
          .dropdown
            = link_to "#", :class => "dropdown-toggle", :id => "difficulty-dropdown" do
              - if @event.difficulty_level.nil?
                Difficulty Level
              - else
                = @event.difficulty_level.title
              <b class="caret"></b>
            %ul.dropdown-menu
              - @difficulty_levels.each do |difficulty|
                %li= link_to difficulty.title, admin_conference_event_path(@conference.short_title, @event, :difficulty_level_id => difficulty.id) ,
                  :method => :put, :difficulty_level_id => difficulty.id
      - if !@event.room.nil?
        %tr
          %td
            %b Room
          %td
            = @event.room.name
      - if !@event.start_time.nil?
        %tr
          %td
            %b Scheduled time
          %td
            = @event.start_time
      %tr
        %td
          %b Submitter
        %td
          = link_to @event.submitter.public_name, admin_person_path(@event.submitter)
          (
          = link_to @event.submitter.email, "mailto: #{@event.submitter.email}"
          )
      %tr
        %td
          %b Biography
        %td
          = simple_format(@event.submitter.biography)
      %tr
        %td
          %b Submitted on
        %td= @event.created_at
      %tr
        %td
          %b Last updated on
        %td= @event.updated_at
      %tr
        %td
          %b Abstract
        %td= simple_format(@event.abstract)
      %tr
        %td
          %b Description
        %td= simple_format(@event.description)

      - if @conference.call_for_papers.rating > 0
        = render :partial => "voting"

    - if @event.event_attachments.size > 0
      %table.table
        %thead
          %th
            %b Filename
          %th
            %b Title
          %th
            %b Size
          %th
            %b Public?
          %th
        %tbody
        - @event.event_attachments.each do |a|
          %tr
            %td
              = link_to a.attachment_file_name, conference_proposal_event_attachment_path(@conference.short_title, @event.id, a.id)
            %td
              = a.title
            %td
              = number_to_human_size a.attachment_file_size
            %td
              - if a.public?
                Public
              - else
                Not Public
            %td
              = link_to "Delete", conference_proposal_event_attachment_path(@conference.short_title, @event.id, a.id),
                :method => :delete, :confirm => "Are you sure you want to delete this attachment?  It's permanant!"

.row
  = link_to "Comments (#{@comment_count})", "#", :id => "event-comment-link"
  #comments-div
    %hr
    %ul.media
      %div
        .row-fluid
          = form_tag(comment_admin_conference_event_path(@conference.short_title, @event.id), :method => :post) do
            = text_area_tag(:comment, "")
            = submit_tag "Add Comment", :class => "btn btn-primary pull-right"
        %br
        - @comments.each do |comment|
          %div
            = raw format_comments(comment)

app/views/admin/events/_voting.html.haml
%table.table#myrating
  %tr
    %td{:style => "width:15%"}
      %b Rating
    %td
      - if @event.average_rating.to_f > 0 
        #{@event.average_rating}/#{@conference.call_for_papers.rating}
      - else
        Rating: 0/#{@conference.call_for_papers.rating}

      - @conference.call_for_papers.rating.times do |counter|
        - if @event.average_rating.to_f.round == counter+1
          = label_tag "label_rating", "", :class => "avgrating", :avgrate => true
          = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
        - else
          = label_tag "label_rating", "", :class => "avgrating"
  %tr
    %td 
      %b Voters
    %td
      = @event.voters.length
      - if @event.voters.length > 0
        (
        = @ratings.map {|x| "#{x.first_name} #{x.last_name}"}.join ', '
        )
  %tr
    %td 
      %b Your vote
    %td
      - @conference.call_for_papers.rating.times do |counter|
        - voted = @event.voted?(@event, current_user.person)
        - if voted && voted.rating == counter+1
          = link_to "", vote_admin_conference_event_path(@conference.short_title, @event, :rating => counter+1), :remote => true, :id =>"label#{counter+1}", :class => "myrating", :voted => true
        - else
          = link_to "", vote_admin_conference_event_path(@conference.short_title, @event, :rating => counter+1), :remote => true, :id =>"label#{counter+1}", :class => "myrating"
      %br

  - if @ratings.length > 0
    - @ratings.each do |rate|
      - unless rate.person_id == current_user.person.id
        %tr
          %td
            = rate.first_name
            = rate.last_name
          %td
            - @conference.call_for_papers.rating.times do |counter|
              - voted = @event.voted?(@event, rate.person)
              - if voted && voted.rating == counter+1
                = label_tag "label#{counter+1}", "", :class => "othersrating", :voted => true
                = javascript_tag "$('label[voted=true]').prevAll().andSelf().addClass('bright');"
              - else
                = label_tag "label#{counter+1}", "", :class => "othersrating"
:javascript   
  $(function () {
    var checkedId = $("a[voted='true']").attr('id');
    $('a[id=' + checkedId + ']').prevAll().andSelf().addClass('bright');
  });

  $(".myrating").hover(
    function() {    // mouseover
        $(this).prevAll().andSelf().addClass('glow');
    },
    function() {  // mouseout
        $(this).siblings().andSelf().removeClass('glow');
    }
  );

  $(".myrating").click(function() {
    $(this).siblings().removeClass("bright");
    $(this).prevAll().andSelf().addClass("bright");
  });

app/views/admin/events/index.html.haml
= render :partial => "events_stats"

.row
  .col-md-12
    %h2
      Events
      - if @events
        = "(#{@events.length})"
    .well
      %table.table.table-striped.table-bordered.table-hover#events
        %thead
          %th
            %b ID
          %th
            %b Title
          - unless @conference.call_for_papers.blank? or !(@conference.call_for_papers.rating > 0)
            %th
              %b Rating
          %th
            %b Submitter
          %th
            %b Speaker
          %th
            %b Type
          %th
            %b Track
          %th
            %b Difficulty
          %th
            %b State
        - @events.each do |event|
          %tr
            %td
              = event.id
            %td
              =link_to event.title, admin_conference_event_path(@conference.short_title, event)
            
            - if @conference.call_for_papers.rating != 0
              %td{:style => "width:96px"}
                - if event.average_rating.to_f > 0 
                  #{event.average_rating}/#{@conference.call_for_papers.rating}
                  %br
                  #{pluralize(event.voters.length, 'voter')}
                  %br
                  - @conference.call_for_papers.rating.times do |counter|
                    - if event.average_rating.to_f.round == counter+1
                      = label_tag "label_rating", "", :class => "avgrating", :avgrate => true
                      = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
                    - else
                      = label_tag "label_rating", "", :class => "avgrating"
                - else
                  0/#{@conference.call_for_papers.rating}
                %br

            - if event.submitter.registrations.count < 1 
              - bgcolor="#F7819F"
            - else 
              - bgcolor=""
            %td{:style=>"background-color: #{bgcolor}"}
              - if !event.submitter.nil?
                =link_to event.submitter.public_name, admin_person_path(event.submitter)
                - if event.submitter.registrations.count < 1
                  (Unregistered!)
              - else
                Unknown submitter
            %td
              - if speaker = event.speakers.first
                = link_to speaker.public_name, admin_person_path(speaker)
              - else
                Unknown speaker
              - l = link_to "Change", edit_admin_conference_event_speaker_path(@conference.short_title, event), :remote => true
              = "(#{l})".html_safe
            %td
              .btn-group
                %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                  - if event.event_type.nil?
                    Event Type
                  - else
                    = event.event_type.title
                  %span.caret
                %ul.dropdown-menu
                  - @event_types.each do |type|
                    %li= link_to type.title, admin_conference_event_path(@conference.short_title, event, :event_type_id => type.id) ,
                      :method => :put, :event_type_id => type.id
            %td
              .btn-group
                %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                  - if event.track.nil?
                    Track
                  - else
                    = event.track.name
                  %span.caret
                %ul.dropdown-menu
                  - @tracks.each do |track|
                    %li= link_to track.name, admin_conference_event_path(@conference.short_title, event, :track_id => track.id) ,
                      :method => :put, :track_id => track.id
            %td
              = event.difficulty_level.title if @conference.use_difficulty_levels && event.difficulty_level
            %td
              - if event.state == "withdrawn"
                Withdrawn
              - else
                .btn-group
                  %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                    = event.state.humanize
                    %span.caret
                  %ul.dropdown-menu{:role=>"menu"}
                    - if event.transition_possible? :accept
                      %li= link_to 'Accept event',
                      accept_admin_conference_event_path(@conference.short_title, event),
                      method: :patch, id: "accept_event_#{event.id}"
                      - if @conference.email_settings.send_on_accepted?
                        %li= link_to 'Accept event (without email)',
                        accept_admin_conference_event_path(@conference.short_title, event, send_mail: false),
                            method: :patch, hint: 'Accept this event without sending an automated email.',
                            id: "accept_event_without_mail_#{event.id}"
                    - if event.transition_possible? :reject
                      %li= link_to 'Reject event',
                      reject_admin_conference_event_path(@conference.short_title, event),
                          method: :patch, confirm: 'Are you sure?', id: "reject_event_#{event.id}"
                      - if @conference.email_settings.send_on_rejected?
                        %li= link_to 'Reject event (without email)',
                        reject_admin_conference_event_path(@conference.short_title, event, send_mail: false),
                            method: :patch, confirm: 'Are you sure?', id: "reject_event_without_mail_#{event.id}"
                    - if event.transition_possible? :restart
                      %li= link_to 'Start review',
                      restart_admin_conference_event_path(@conference.short_title, event),
                          method: :patch, id: "restart_event_#{event.id}"
                    - if event.transition_possible? :confirm
                      %li= link_to 'Confirm event',
                      confirm_admin_conference_event_path(@conference.short_title, event),
                          method: :patch, id: "confirm_event_#{event.id}",
                          hint: 'Confirm that the speaker(s) will be present and that the event will actually take place.'
                    - if event.transition_possible? :cancel
                      %li= link_to 'Cancel event',
                      cancel_admin_conference_event_path(@conference.short_title, event),
                          method: :patch, id: "cancel_event_#{event.id}",
                          hint: 'Mark this event as cancelled. Usually this means that the speakers had to cancel their appearance.'

:javascript
  $(document).ready(function() {
      $('#events').dataTable( {
        "bPaginate": false
      } );
  } );