config/routes.rb
Osem::Application.routes.draw do

  get 'conference/show'

  devise_for :users, :controllers => { :registrations => :registrations }, :path => 'accounts'

  namespace :admin do
    resources :users
    resources :people
    resources :conference do
      get "/schedule" => "schedule#show"
      patch "/schedule" => "schedule#update"
      get "/stats" => "stats#index"
      get "/venue" => "venue#show", :as => "venue_info"
      patch "/venue" => "venue#update", :as => "venue_update"
      get "/dietary_choices" => "dietchoices#show", :as => "dietary_list"
      patch "/dietary_choices" => "dietchoices#update", :as => "dietary_update"
      get "/volunteers_list" => "volunteers#show"
      get "/volunteers" => "volunteers#index", :as => "volunteers_info"
      patch "/volunteers" => "volunteers#update", :as => "volunteers_update"

      patch '/registrations/change_field' => 'registrations#change_field'
      resources :registrations

      resources :difficulty_levels, only: [:show, :update, :index]

      resources :rooms, only: [:show, :update, :index]

      resources :tracks, only: [:show, :update, :index]

      resources :eventtypes, only: [:show, :index] do
        collection do
          patch :update
        end
      end

      resources :social_events, only: [:show, :update, :index]

      resources :supporter_levels, only: [:show, :update, :index]

      resources :emails, only: [:show, :update, :index]

      resources :callforpapers, only: [:create] do
        collection do
          patch :update
          get :show
        end
      end

      patch "/questions/update_conference" => "questions#update_conference"
      resources :questions

      resources :events do
        member do
          post :comment
          patch :accept
          patch :confirm
          patch :cancel
          patch :reject
          patch :unconfirm
          patch :restart
          get :vote
        end
        resource :speaker, :only => [:edit, :update]
      end

      resources :supporters
    end
  end

  resources :conference, only: [:show] do
    resources :proposal do
      resources :event_attachment, :controller => "event_attachments"
      patch '/confirm' => 'proposal#confirm'
      patch '/restart' => 'proposal#restart'
    end
    resource :schedule, :only => [] do
      get "/" => "schedule#index"
    end
    member do
      get "/register" => "conference_registration#register"
      patch "/register" => "conference_registration#update"
      delete "/register" => "conference_registration#unregister"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, :only => :index do
        resources :conferences, :only => :index
        resources :rooms, :only => :index
        resources :tracks, :only => :index
        resources :speakers, :only => :index
        resources :events, :only => :index
      end
      resources :rooms, :only => :index
      resources :tracks, :only => :index
      resources :speakers, :only => :index
      resources :events, :only => :index
    end
  end

  get "/admin" => redirect("/admin/conference")

  root :to => "home#index"
end

app/models/conference.rb
##
# This class represents a conference

class Conference < ActiveRecord::Base
  attr_accessible :title, :short_title, :social_tag, :contact_email, :timezone, :html_export_path,
                  :start_date, :end_date, :rooms_attributes, :tracks_attributes, :dietary_choices_attributes,
                  :use_dietary_choices, :use_supporter_levels, :supporter_levels_attributes, :social_events_attributes,
                  :event_types_attributes, :registration_start_date, :registration_end_date, :logo,
		              :questions_attributes, :question_ids, :answers_attributes, :answer_ids,
                  :difficulty_levels_attributes, :use_difficulty_levels,
                  :use_vpositions, :use_vdays, :vdays_attributes, :vpositions_attributes, :use_volunteers,
                  :media_id, :media_type, :color, :description,
                  :registration_description, :ticket_description

  has_paper_trail

  has_and_belongs_to_many :questions

  has_one :email_settings, :dependent => :destroy
  has_one :call_for_papers, :dependent => :destroy
  has_many :social_events, :dependent => :destroy
  has_many :supporter_registrations, :dependent => :destroy
  has_many :supporter_levels, :dependent => :destroy
  has_many :dietary_choices, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :event_types, :dependent => :destroy
  has_many :tracks, :dependent => :destroy
  has_many :difficulty_levels, :dependent => :destroy
  has_many :rooms, :dependent => :destroy
  has_many :registrations, :dependent => :destroy
  has_many :vdays, :dependent => :destroy
  has_many :vpositions, :dependent => :destroy
  has_many :vchoices, :dependent => :destroy

  belongs_to :venue

  accepts_nested_attributes_for :rooms, :reject_if => proc {|r| r["name"].blank?}, :allow_destroy => true
  accepts_nested_attributes_for :tracks, :reject_if => proc {|r| r["name"].blank?}, :allow_destroy => true
  accepts_nested_attributes_for :difficulty_levels, :allow_destroy => true
  accepts_nested_attributes_for :social_events, :allow_destroy => true
  accepts_nested_attributes_for :venue
  accepts_nested_attributes_for :dietary_choices, :allow_destroy => true
  accepts_nested_attributes_for :supporter_levels, :allow_destroy => true
  accepts_nested_attributes_for :event_types, :allow_destroy => true
  accepts_nested_attributes_for :email_settings
  accepts_nested_attributes_for :questions, :allow_destroy => true
  accepts_nested_attributes_for :vdays, :allow_destroy => true
  accepts_nested_attributes_for :vpositions, :allow_destroy => true

  has_attached_file :logo,
                    :styles => {:thumb => "100x100>", :large => "300x300>" }

  validates_attachment_content_type :logo,
                                    :content_type => [/jpg/, /jpeg/, /png/, /gif/],
                                    :size => { :in => 0..500.kilobytes }

  validates_presence_of :title,
                        :short_title,
                        :social_tag,
                        :start_date,
                        :end_date
  validates_uniqueness_of :short_title
  validates_format_of :short_title, :with => /\A[a-zA-Z0-9_-]*\z/
  before_create :generate_guid
  before_create :create_venue
  before_create :create_email_settings
  before_create :add_color

  def self.media_types
    media_types = {:youtube => 'YouTube', :slideshare => 'SlideShare',  :flickr => 'Flickr', :vimeo => 'Vimeo', :speakerdeck => 'Speakerdeck', :instagram => 'Instagram'}
    return media_types
  end


  ##
  # Checks if the user is registered to the conference
  #
  # ====Args
  # * +user+ -> The user we check for
  # ====Returns
  # * +nil+ -> If the user doesn't exist
  # * +false+ -> If the user is registered
  # * +true+ - If the user isn't registered
  def user_registered? user
    return nil if user.nil?
    return nil if user.person.nil?

    if self.registrations.where(:person_id => user.person.id).count == 0
      logger.debug("User #{user.email} isn't registered to self.title")
      return false
    else
      return true
    end
  end

  ##
  # Checks if the registration for the conference is currently open
  #
  # ====Returns
  # * +false+ -> If the conference dates are not set or today isn't in the
  #   registration period.
  # * +true+ -> If today is in the registration period.
  def registration_open?
    today = Date.current
    if registration_dates_given?
      (registration_start_date..registration_end_date).cover?(today)
    else
      false
    end
  end

  ##
  # Checks if the registration dates for the conference are provided
  #
  # ====Returns
  # * +false+ -> If the conference registration dates are not set
  # * +true+ -> If conference registration dates are set
  def registration_dates_given?
    if registration_start_date.blank? || registration_end_date.blank?
      false
    else
      true
    end
  end

  ##
  # Checks if the call for papers for the conference is currently open
  #
  # ====Returns
  # * +false+ -> If the CFP is not set or today isn't in the CFP period.
  # * +true+ -> If today is in the CFP period.
  def cfp_open?
    today = Date.current
    cfp = self.call_for_papers
    if !cfp.nil? && (cfp.start_date.. cfp.end_date).cover?(today)
      return true
    end

    return false
  end

  ##
  # Returns an array with the summarized event submissions per week.
  #
  # ====Returns
  #  * +Array+ -> e.g. [0, 3, 3, 5] -> first week 0 events, second week 3 events.
  def get_submissions_per_week
    result = []

    if call_for_papers && events
      submissions = events.group("strftime('%W', created_at)").count
      start_week = call_for_papers.start_week
      weeks = call_for_papers.weeks
      result = calculate_items_per_week(start_week, weeks, submissions)
    end
    result
  end

  ##
  # Returns an array with the summarized registrations per week.
  #
  # ====Returns
  #  * +Array+ -> e.g. [0, 3, 3, 5] -> first week 0, second week 3 registrations
  def get_registrations_per_week
    result = []

    if registrations &&
        registration_start_date &&
        registration_end_date

      reg = registrations.group("strftime('%W', created_at)").count
      start_week = get_registration_start_week
      weeks = registration_weeks
      result = calculate_items_per_week(start_week, weeks, reg)
    end
    result
  end

  ##
  # Calculates how many weeks the registration is.
  #
  # ====Returns
  # * +Integer+ -> start week
  def registration_weeks
    result = 0
    weeks = 0
    if registration_start_date && registration_end_date
      weeks = Date.new(registration_start_date.year, 12, 31).
          strftime('%W').to_i

      result = get_registration_end_week - get_registration_start_week + 1
    end
    result < 0 ? result + weeks : result
  end

  ##
  # Calculates how many weeks call for papers is.
  #
  # ====Returns
  # * +Integer+ -> weeks
  def cfp_weeks
    result = 0
    if call_for_papers
      result = call_for_papers.weeks
    end
    result
  end

  ##
  # Calculates the end week of the registration
  #
  # ====Returns
  # * +Integer+ -> start week
  def get_registration_start_week
    registration_start_date.strftime('%W').to_i
  end

  ##
  # Calculates the start week of the registration
  #
  # ====Returns
  # * +Integer+ -> start week
  def get_registration_end_week
    registration_end_date.strftime('%W').to_i
  end

  ##
  # Checks if the conference is pending.
  #
  # ====Returns
  # * +false+ -> If the conference start date is in the past.
  # * +true+ -> If the conference start date is in the future.
  def pending?
    start_date > Date.today
  end

  ##
  # Returns a hash with booleans with the required conference options.
  #
  # ====Returns
  # * +hash+ -> true -> filled / false -> missing
  def get_status
    result = {}
    result['registration'] = !!registration_start_date && !!registration_end_date
    result['cfp'] = !!call_for_papers
    result['venue'] = !!venue && !!venue.name && !!venue.address && !!venue.website
    result['rooms'] = rooms.count > 0
    result['tracks'] = tracks.count > 0
    result['event_types'] = event_types.count > 0
    result['difficulty_levels'] = difficulty_levels.count > 0
    result['process'] = (result.select { |k, v| v }.length / result.length.to_f * 100).round(0).to_s
    result['short_title'] = short_title
    result
  end

  ##
  # Returns a hash with person => submissions ordered by submissions for all conferences
  #
  # ====Returns
  # * +hash+ -> person: submissions
  def self.get_top_submitter(limit = 5)
    submitter = EventPerson.where('event_role = ?', 'submitter').limit(limit).group(:person_id)
    counter = submitter.count
    calculate_person_submission_hash(submitter, counter)
  end

  ##
  # Returns a hash with person => submissions ordered by submissions
  #
  # ====Returns
  # * +hash+ -> person: submissions
  def get_top_submitter(limit = 5)
    submitter = EventPerson.joins(:event).
        where('event_role = ? and conference_id = ?', 'submitter', id).
        limit(limit).group(:person_id)

    counter = submitter.count
    Conference.calculate_person_submission_hash(submitter, counter)
  end

  private

  ##
  # Returns a hash with person => submissions ordered by submissions for all conferences
  #
  # ====Returns
  # * +hash+ -> person: submissions
  def self.calculate_person_submission_hash(submitter, counter)
    result = {}
    submitter.each do |s|
      result[s.person] = counter[s.person_id]
    end
    result
  end

  ##
  # Creates a venue and sets self.venue_id to it's id. Used as before_create.
  #
  def create_venue
    self.venue_id = Venue.create.id
    true
  end

  ##
  # Creates a EmailSettings association proxy. Used as before_create.
  #
  def create_email_settings
    build_email_settings
    true
  end

  ##
  # Creates a UID for the conference. Used as before_create.
  #
  def generate_guid
    begin
      guid = SecureRandom.urlsafe_base64
    end while Person.where(:guid => guid).exists?

app/controllers/admin/conference_controller.rb
class Admin::ConferenceController < ApplicationController
  before_filter :verify_organizer

  def index
    @total_user = User.count
    @new_user = User.where('created_at > ?', current_user.last_sign_in_at).count

    @total_reg = Registration.count
    @new_reg = Registration.where('created_at > ?', current_user.last_sign_in_at).count

    @total_submissions = Event.count
    @new_submissions = Event.where('created_at > ?', current_user.last_sign_in_at).count

    @conferences = Conference.select('id, short_title, color, start_date,
                                      registration_end_date, registration_start_date')

    @recent_users = User.limit(5).order(created_at: :desc)
    @recent_events = Event.limit(5).order(created_at: :desc)
    @recent_registrations = Registration.limit(5).order(created_at: :desc)

    @top_submitter = Conference.get_top_submitter

    @submissions = {}
    @cfp_weeks = [0]

    @registrations = {}
    @registration_weeks = [0]

    @conferences.each do |c|
      # Event submissions over time chart
      @submissions[c.short_title] = c.get_submissions_per_week
      @cfp_weeks.push(@submissions[c.short_title].length)

      # Conference registrations over time chart
      @registrations[c.short_title] = c.get_registrations_per_week
      @registration_weeks.push(@registrations[c.short_title].length)
    end

    @cfp_weeks = @cfp_weeks.max
    @submissions = normalize_array_length(@submissions, @cfp_weeks)
    @cfp_weeks = @cfp_weeks > 0 ? (1..@cfp_weeks).to_a : 1

    @registration_weeks = @registration_weeks.max
    @registrations = normalize_array_length(@registrations, @registration_weeks)
    @registration_weeks = @registration_weeks > 0 ? (1..@registration_weeks).to_a : 1

    # Redirect to new form if there is no conference
    if Conference.count == 0
      redirect_to new_admin_conference_path
      return
    end
  end

  def new
    @conference = Conference.new
  end

  def create
    @conference = Conference.new(params[:conference])
    if @conference.valid?
      @conference.save
      redirect_to(admin_conference_path(id: @conference.short_title),
                  notice: 'Conference was successfully created.')
    else
      redirect_to(new_admin_conference_path,
                  alert: 'Creating the Conference failed.' \
                          "#{@conference.errors.full_messages.join('. ')}.")
    end
  end

  def update
    @conference = Conference.find_by(short_title: params[:id])
    short_title = @conference.short_title
    if @conference.update_attributes(params[:conference])
      redirect_to(edit_admin_conference_path(id: @conference.short_title),
                  notice: 'Conference was successfully updated.')
    else
      redirect_to(edit_admin_conference_path(id: short_title),
                  alert: 'Updating conference failed. ' \
                  "#{@conference.errors.full_messages.join('. ')}.")
    end
  end

  def show
    @conference = Conference.find_by(short_title: params[:id])
    @conference_progress = @conference.get_status
    @top_submitter = @conference.get_top_submitter
    respond_to do |format|
      format.html
      format.json { render json: @conference.to_json }
    end
  end

  def edit
    @conferences = Conference.all
    @conference = Conference.find_by(short_title: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @conference.to_json }
    end
  end
end

app/controllers/api/v1/conferences_controller.rb
class Api::V1::ConferencesController < Api::BaseController
  respond_to :json

  def index
    if params[:conference_id].blank?
      conferences = Conference.all
    else
      conferences = Conference.find_all_by_guid(params[:conference_id])
    end
    render :json => conferences, :serializer => ConferencesArraySerializer
  end
end

app/controllers/conference_controller.rb
class ConferenceController < ApplicationController
  def show
    @conference = Conference.find_by_short_title(params[:id])
  end
end

app/views/admin/conference/_recent_registrations.html.haml
- if recent_registrations && !recent_registrations.empty?
  %table.table
    %thead
      %tr
        %th #
        %th Public Name
        %th Conference
        %th Date
      - recent_registrations.each_with_index do |registration, index|
        %tbody
          %tr
            %td #{index + 1}
            %td #{registration.public_name}
            %td #{registration.conference.title}
            %td #{registration.created_at.strftime('%m/%d/%Y')}
- else
  %h5.text-warning.text-center
    No registrations!

app/views/admin/conference/_recent_submissions.html.haml
- if recent_events && !recent_events.empty?
  %table.table
    %thead
      %tr
        %th #
        %th Submitter
        %th Title
        %th Conference
        %th Status
      - recent_events.each_with_index do |event, index|
        %tbody
          %tr
            %td #{index + 1}
            %td #{event.submitter}
            %td #{event.title}
            %td #{event.conference.title}
            %td
              .span{'class'=>label_for(event.state)} #{event.state.humanize}
- else
  %h5.text-warning.text-center
    No submissions!

app/views/admin/conference/_recent_users.html.haml
- if recent_users && !recent_users.empty?
  %table.table
    %thead
      %tr
        %th #
        %th E-Mail
        %th Date registered
        %th Status
    - recent_users.each_with_index do |user, index|
      %tbody
        %tr
          %td #{index}
          %td #{user.email}
          %td #{user.created_at.strftime('%m/%d/%Y')}
          %td
            - if user.confirmed?
              %span.label.label-success Confirmed
            -else
              %span.label.label-danger Unconfirmed
- else
  %h5.text-warning.text-center
    No sign ups!

app/views/admin/conference/_registrations.html.haml
.well#registrations
  .row
    .text-center
      %h4 Conference registrations over time
  .row
    .registrationsChart{"data-chart"=>"#{registrations.to_json}", "data-conferences"=>"#{conferences.to_json}", "data-weeks"=>"#{registration_weeks.to_json}"}
      %canvas#registrationsChart{"data-name"=>"registrations"}
  .row
    .text-center
      weeks
  .row
    .conferenceCheckboxes#registrationsCheckboxes
      - conferences.each do |conference|
        %div
          %span{"style"=>"border-bottom: 3px solid #{conference.color};", "data-chart"=> "registrations"}
            - if conference.pending?
              %input{"type"=>"checkbox", "name"=>"#{conference.short_title}", "checked"=>"checked"}
            - else
              %input{"type"=>"checkbox", "name"=>"#{conference.short_title}"}
            #{conference.short_title}

app/views/admin/conference/_submissions.html.haml
.well#submissions
  .row
    .text-center
      %h4 Event submissions over time
  .row
    .submissionsChart{"data-chart"=>"#{submissions.to_json}", "data-conferences"=>"#{conferences.to_json}", "data-weeks"=>"#{cfp_weeks.to_json}"}
      %canvas#submissionsChart{"data-name"=>"submissions"}
  .row
    .text-center
      weeks
  .row
    .conferenceCheckboxes#submissionsCheckboxes
      - conferences.each do |conference|
        %div
          %span{"style"=>"border-bottom: 3px solid #{conference.color};", "data-chart"=> "submissions"}
            - if conference.pending?
              %input{"type"=>"checkbox", "name"=>"#{conference.short_title}", "checked"=>"checked"}
            - else
              %input{"type"=>"checkbox", "name"=>"#{conference.short_title}"}
            #{conference.short_title}

app/views/admin/conference/_todo_list.html.haml
.list-group
  %li.list-group-item
    %h4
      Conference progress
    .progress
      .progress-bar{ 'role'=>'progressbar', 'aria-valuenow'=>"#{conference_progress['process']}", 'aria-valuemin'=>'0',
                    'aria-valuemax'=>'100', 'style'=>"width: #{conference_progress['process']}%;" }
        = conference_progress['process'] + '%'
  %li{'class'=>class_for_todo(conference_progress['registration'])}
    %span{'class'=>icon_for_todo(conference_progress['registration'])}
    = link_to 'Set up registration period', edit_admin_conference_path(conference_progress['short_title'], :anchor => 'conference-end-datepicker')
  %li{'class'=>class_for_todo(conference_progress['cfp'])}
    %span{'class'=>icon_for_todo(conference_progress['cfp'])}
    = link_to 'Set up call for papers', admin_conference_callforpapers_path(conference_progress['short_title'])
  %li{'class'=>class_for_todo(conference_progress['venue'])}
    %span{'class'=>icon_for_todo(conference_progress['venue'])}
    = link_to 'Add venue', admin_conference_venue_info_path(conference_progress['short_title'])
  %li{'class'=>class_for_todo(conference_progress['rooms'])}
    %span{'class'=>icon_for_todo(conference_progress['rooms'])}
    = link_to 'Add rooms', admin_conference_rooms_path(conference_progress['short_title'])
  %li{'class'=>class_for_todo(conference_progress['tracks'])}
    %span{'class'=>icon_for_todo(conference_progress['tracks'])}
    = link_to 'Add tracks', admin_conference_tracks_path(conference_progress['short_title'])
  %li{'class'=>class_for_todo(conference_progress['event_types'])}
    %span{'class'=>icon_for_todo(conference_progress['event_types'])}
    = link_to 'Add event types', admin_conference_eventtypes_path(conference_progress['short_title'])
  %li{'class'=>class_for_todo(conference_progress['difficulty_levels'])}
    %span{'class'=>icon_for_todo(conference_progress['difficulty_levels'])}
    = link_to 'Add difficulty levels', admin_conference_difficulty_levels_path(conference_progress['short_title'])

app/views/admin/conference/_top_boxes.html.haml
.col-sm-4
  .dashbox.well.well-sm.text-center
    .icon
      %i.glyphicon.glyphicon-user
    .text
      %label.text-muted total user: #{@total_user}
      %label.text-muted new user: #{@new_user}
.col-sm-4
  .dashbox.well.well-sm.text-center
    .icon
      %i.glyphicon.glyphicon-star
    .text
      %label.text-muted total registrations: #{@total_reg}
      %label.text-muted new registrations: #{@new_reg}
.col-sm-4
  .dashbox.well.well-sm.text-center
    .icon
      %i.glyphicon.glyphicon-comment
    .text
      %label.text-muted total submissions: #{@total_submissions}
      %label.text-muted new submissions: #{@new_submissions}

app/views/admin/conference/_top_submitter.html.haml
.row
  %h3
    Top Submitter
  - if @top_submitter && !@top_submitter.empty?
    - @top_submitter.each do |key, value|
      .row.top-submitter
        .col-md-2
          = image_tag(key.gravatar_url(size: '25'), title: "Yo #{key.public_name}!", :alt => '', 'class'=>'img-circle img-responsive text-center')
        .col-md-10
          %h4
            #{key}
            %div
              %small
                #{pluralize(value, 'submission')}
  - else
    %h4.text-warning
      No submissions!

app/views/admin/conference/edit.html.haml
.row
  .col-md-8
    = semantic_form_for(@conference, :url => admin_conference_path(@conference.short_title),:html => {:multipart => true}) do |f|
      = f.input :title, :hint => "The full name of the conference, such as 'OpenSUSE Conference 2013'"
      = f.input :short_title, :hint => "A short title, such as 'osc2013', to be used in URLs"
      = f.input :social_tag, :hint => "The hashtag you'll use on Twitter and Google+.  Don't include the '#' sign!'"
      = f.input :contact_email, :hint => "Contact email address for your conference. Will be used as reply-to address in emails sent out by the system."
      = f.input :color, :hint => "The color will be used eg for the dashboard.", :input_html => {:size => 6, :type => "color"}
      = f.input :description, hint: 'This description will be shown in the program segement of the Splash'

      = f.inputs :name => "Scheduling" do
        = f.input :timezone, :as => :time_zone, :hint => "The conference time zone"
        = f.input :start_date, :as => :string, :input_html => { :id => "conference-start-datepicker", :readonly => "readonly"  }
        = f.input :end_date, :as => :string, :input_html => { :id => "conference-end-datepicker", :readonly => "readonly"  }
        = f.input :registration_start_date, :as => :string, :input_html => { :id => "conference-reg-start-datepicker", :readonly => "readonly"  }
        = f.input :registration_end_date, :as => :string, :input_html => { :id => "conference-reg-end-datepicker", :readonly => "readonly"  }
      = f.input :registration_description, hint: 'This description will appear in registration segment of the splash'
      = f.input :ticket_description, hint: 'This will appear in the Tickets segment of the splash'

      = f.inputs :name => "Media" do
        - if !@conference.logo.blank?
          = image_tag @conference.logo(:thumb)
        = f.input :logo, :label => "Conference Logo", :hint => "This will be displayed on the front page."
        = f.input :media_type, :as => :select, :label => "Conference Promo Media Type", :class=>"form-control", :collection => Conference.media_types.values, :include_blank => false, :hint => "This media-item will be used to represent this conference at various places in OSEM."
        = f.input :media_id, :label => "Conference Promo Media ID", :as => :string
        %p{:class => "help-block media-type", :id => "youtube-help"} Go to your YouTube video, click on "share" and copy everything behind http://youtu.be/"
        %p{:class => "help-block media-type", :id => "slideshare-help", :style => "display:none"} Go to your SlideShare, click on "share" -> "embed" and copy the id
        %p{:class => "help-block media-type", :id => "flickr-help", :style => "display:none"} Go to your flickr image, click on "Grab the link" -> "Show short url" and copy everything behind https://flic.kr/p/
        %p{:class => "help-block media-type", :id => "vimeo-help", :style => "display:none"} Go to your vimeo video, click on "share" and copy everything behind http://vimeo.com/
        %p{:class => "help-block media-type", :id => "speakerdeck-help", :style => "display:none"} Go to your SpeakerDeck, click on "share" -> "embed" and copy the data-id
        %p{:class => "help-block media-type", :id => "instagram-help", :style => "display:none"} Go to your Instagram photo page and copy everything behind instagram.com/p/ (without trailing /# hash symbol)
      = f.action :submit, :as => :button, :button_html => {:class => "btn btn-primary"}

app/views/admin/conference/new.html.haml
.row
  .col-md-8
    = semantic_form_for(@conference, :url => admin_conference_index_path) do |f|
      = f.inputs 'Basic Information' do
        = f.input :title, hint: "The name of your conference as it shall appear throughout the site. Example: 'OpenSUSE Conference 2013'",
                          input_html: { required: 'required' }
        = f.input :short_title, hint: "A short and unique handle for your conference, using only lower-case letters, numbers and underscores. This will be used to identify your conference in URLs etc. Example: 'froscon2011'",
                                input_html: { required: 'required' }
        = f.input :social_tag, hint: "The hashtag you'll use on Twitter and Google+.  Don't include the '#' sign!'",
                               input_html: { required: 'required' }
        = f.input :contact_email, hint: 'Contact email address for your conference. Will be used as reply-to address in emails sent out by the system.'
      = f.inputs 'Scheduling' do
        = f.input :timezone, as: :time_zone, hint: 'Please select in what time zone your conference will take place.'
        = f.input :start_date, as: :string, input_html: { id: 'conference-start-datepicker', readonly: 'readonly', required: 'required' }
        = f.input :end_date, as: :string, input_html: { id: 'conference-end-datepicker', readonly: 'readonly', required: 'required'  }
      = f.actions do
        = f.action :submit, button_html: {class: 'btn btn-success pull-right'}

app/views/admin/conference/show.html.haml
%h1
  %span.glyphicon.glyphicon-dashboard
  Dashboard for #{@conference.title}
%hr
.row
  .col-md-4
    = render partial: 'todo_list', locals: { conference_progress: @conference_progress }
  .col-md-4
    = render partial: 'top_submitter', locals: {top_submitter: @top_submitter}