config/routes.rb
Osem::Application.routes.draw do

  get 'conference/show'

  devise_for :users, :controllers => { :registrations => :registrations }, :path => 'accounts'

  namespace :admin do
    resources :users
    resources :people
    resources :conference do
      get "/schedule" => "schedule#show"
      patch "/schedule" => "schedule#update"
      get "/stats" => "stats#index"
      get "/venue" => "venue#show", :as => "venue_info"
      patch "/venue" => "venue#update", :as => "venue_update"
      get "/dietary_choices" => "dietchoices#show", :as => "dietary_list"
      patch "/dietary_choices" => "dietchoices#update", :as => "dietary_update"
      get "/volunteers_list" => "volunteers#show"
      get "/volunteers" => "volunteers#index", :as => "volunteers_info"
      patch "/volunteers" => "volunteers#update", :as => "volunteers_update"

      patch '/registrations/change_field' => 'registrations#change_field'
      resources :registrations

      resources :difficulty_levels, only: [:show, :update, :index]

      resources :rooms, only: [:show, :update, :index]

      resources :tracks, only: [:show, :update, :index]

      resources :eventtypes, only: [:show, :index] do
        collection do
          patch :update
        end
      end

      resources :social_events, only: [:show, :update, :index]

      resources :supporter_levels, only: [:show, :update, :index]

      resources :emails, only: [:show, :update, :index]

      resources :callforpapers, only: [:create] do
        collection do
          patch :update
          get :show
        end
      end

      patch "/questions/update_conference" => "questions#update_conference"
      resources :questions

      resources :events do
        member do
          post :comment
          patch :accept
          patch :confirm
          patch :cancel
          patch :reject
          patch :unconfirm
          patch :restart
          get :vote
        end
        resource :speaker, :only => [:edit, :update]
      end

      resources :supporters
    end
  end

  resources :conference, only: [:show] do
    resources :proposal do
      resources :event_attachment, :controller => "event_attachments"
      patch '/confirm' => 'proposal#confirm'
      patch '/restart' => 'proposal#restart'
    end
    resource :schedule, :only => [] do
      get "/" => "schedule#index"
    end
    member do
      get "/register" => "conference_registration#register"
      patch "/register" => "conference_registration#update"
      delete "/register" => "conference_registration#unregister"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, :only => :index do
        resources :conferences, :only => :index
        resources :rooms, :only => :index
        resources :tracks, :only => :index
        resources :speakers, :only => :index
        resources :events, :only => :index
      end
      resources :rooms, :only => :index
      resources :tracks, :only => :index
      resources :speakers, :only => :index
      resources :events, :only => :index
    end
  end

  get "/admin" => redirect("/admin/conference")

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @today = Date.current
    @current = Conference.where("end_date >= ?", @today).order("start_date ASC")
  end
end

app/helpers/home_helper.rb
##
# This class contains helper for the home views.

module HomeHelper

  ##
  # Returns a string build from the start and end date of the given conference.
  #
  # If the conference starts and ends in the same month and year
  # * %B %d - %d, %Y (January 17 - 21 2014)
  # If the conference ends in another month but in the same year
  # * %B %d - %B %d, %Y (January 31 - February 02 2014)
  # All other cases
  # * %B %d, %Y - %B %d, %Y (December 30, 2013 - January 02, 2014)
  def conference_date_string(conf)
    date_string(conf.start_date, conf.end_date)
  end

  def date_string(start_date, end_date)
    startstr = 'Unknown - '
    endstr = 'Unknown'
    # When the conference  in the same month
    if start_date.month == end_date.month && start_date.year == end_date.year
      startstr = start_date.strftime('%B %d - ')
      endstr = end_date.strftime('%d, %Y')
    elsif start_date.month != end_date.month && start_date.year == end_date.year
      startstr = start_date.strftime('%B %d - ')
      endstr = end_date.strftime('%B %d, %Y')
    else
      startstr = start_date.strftime('%B %d, %Y - ')
      endstr = end_date.strftime('%B %d, %Y')
    end

    result = startstr + endstr
    result
  end
end

app/views/home/_conference_details.html.haml
.row
  .col-md-12
    .well
      .row
        .col-md-4.text-center
          = image_tag(conference.logo(:original), class: 'img-responsive') if conference.logo?
        .col-md-6
          %h3
            = conference.title
            %small
              %b
              = conference_date_string(conference)
          - if conference.venue.name and conference.venue.website and conference.venue.address
            %p
              %small
                = link_to conference.venue.name, conference.venue.website
                ,
                \#{link_to conference.venue.address, "http://maps.google.com/maps?q=#{conference.venue.address}"}
          - if conference.venue.description
            = simple_format(conference.venue.description, class: 'lead')
        .col-md-2
          .btn-group-vertical
            - if !@conference || @conference != conference
              = link_to "View Conference", conference_path(conference.short_title), :class =>"btn btn-default"
            - if conference.registration_open?
              - if conference.user_registered?(current_user)
                = link_to "Modify Registration", register_conference_path(conference.short_title), :class =>"btn btn-default"
              - else
                = link_to "Register", register_conference_path(conference.short_title), :class =>"btn btn-success"
            = link_to "Schedule", conference_schedule_path(conference.short_title), :class =>"btn btn-default" if conference.call_for_papers and conference.call_for_papers.schedule_public
            - if !current_user.nil? && current_user.person.proposal_count(conference) > 0
              = link_to "View My Proposals", conference_proposal_index_path(conference.short_title), :class =>"btn btn-default"
            - elsif conference.cfp_open?
              = link_to "Submit Proposal", conference_proposal_index_path(conference.short_title), :class =>"btn btn-default"

app/views/home/index.html.haml
.row
  .col-md-12.page-header
    %h2.text-center Upcoming Conferences
- @current.each do |conference|
  = render :partial => "conference_details", :locals => {:conference => conference}