config/routes.rb
Osem::Application.routes.draw do

  get 'conference/show'

  devise_for :users, :controllers => { :registrations => :registrations }, :path => 'accounts'

  namespace :admin do
    resources :users
    resources :people
    resources :conference do
      get "/schedule" => "schedule#show"
      patch "/schedule" => "schedule#update"
      get "/stats" => "stats#index"
      get "/venue" => "venue#show", :as => "venue_info"
      patch "/venue" => "venue#update", :as => "venue_update"
      get "/dietary_choices" => "dietchoices#show", :as => "dietary_list"
      patch "/dietary_choices" => "dietchoices#update", :as => "dietary_update"
      get "/volunteers_list" => "volunteers#show"
      get "/volunteers" => "volunteers#index", :as => "volunteers_info"
      patch "/volunteers" => "volunteers#update", :as => "volunteers_update"

      patch '/registrations/change_field' => 'registrations#change_field'
      resources :registrations

      resources :difficulty_levels, only: [:show, :update, :index]

      resources :rooms, only: [:show, :update, :index]

      resources :tracks, only: [:show, :update, :index]

      resources :eventtypes, only: [:show, :index] do
        collection do
          patch :update
        end
      end

      resources :social_events, only: [:show, :update, :index]

      resources :supporter_levels, only: [:show, :update, :index]

      resources :emails, only: [:show, :update, :index]

      resources :callforpapers, only: [:create] do
        collection do
          patch :update
          get :show
        end
      end

      patch "/questions/update_conference" => "questions#update_conference"
      resources :questions

      resources :events do
        member do
          post :comment
          patch :accept
          patch :confirm
          patch :cancel
          patch :reject
          patch :unconfirm
          patch :restart
          get :vote
        end
        resource :speaker, :only => [:edit, :update]
      end

      resources :supporters
    end
  end

  resources :conference, only: [:show] do
    resources :proposal do
      resources :event_attachment, :controller => "event_attachments"
      patch '/confirm' => 'proposal#confirm'
      patch '/restart' => 'proposal#restart'
    end
    resource :schedule, :only => [] do
      get "/" => "schedule#index"
    end
    member do
      get "/register" => "conference_registration#register"
      patch "/register" => "conference_registration#update"
      delete "/register" => "conference_registration#unregister"
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, :only => :index do
        resources :conferences, :only => :index
        resources :rooms, :only => :index
        resources :tracks, :only => :index
        resources :speakers, :only => :index
        resources :events, :only => :index
      end
      resources :rooms, :only => :index
      resources :tracks, :only => :index
      resources :speakers, :only => :index
      resources :events, :only => :index
    end
  end

  get "/admin" => redirect("/admin/conference")

  root :to => "home#index"
end

app/models/person.rb
class Person < ActiveRecord::Base
  include Gravtastic
  gravtastic :size => 32

  attr_accessible :email, :first_name, :last_name, :public_name, :biography, :company, :avatar, :irc_nickname, :mobile, :tshirt, :languages, :volunteer_experience

  belongs_to :user, :inverse_of => :person
  has_many :event_people, :dependent => :destroy
  has_many :events, -> { uniq }, :through => :event_people
  has_many :registrations, :dependent => :destroy
  has_many :votes, :dependent => :destroy
  has_many :voted_events, :through => :votes, :source => :events

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :email, :presence => true
  validate :biography_limit

  before_create :generate_guid
  before_save :set_public_name

  has_attached_file :avatar,
                    :styles => {:tiny => "16x16>", :small => "32x32>", :large => "128x128>"},
                    :default_url => "person_:style.png"
  validates_attachment_content_type :avatar, :content_type => [/jpg/, /jpeg/, /png/, /gif/]

  alias_attribute :affiliation, :company

  def to_s
    if self.public_name.empty?
      self.first_name + " " + self.last_name
    else
      self.public_name
    end
  end

  def attending_conference? conference
    Registration.where(:conference_id => conference.id,
                       :person_id => self.id).count
  end


  def proposals conference
    events.where('conference_id = ? AND event_people.event_role=?', conference.id, 'submitter')
  end

  def proposal_count conference
    proposals(conference).count
  end

  def biography_word_count
    if self.biography.nil?
      0
    else
      self.biography.split.size
    end
  end

  def self.find_person_by_user_id user_id
    Person.where(:user_id => user_id).first
  end

  def confirmed?
    if User.exists?(self.user_id)
      user = User.find(self.user_id)
      if user.confirmed?
        true
      else
        false
      end
    else
      false
    end
  end

  private
  def biography_limit
    if !self.biography.nil? && self.biography.split.size > 150
      errors.add(:abstract, "cannot have more than 150 words")
    end
  end

  def set_public_name
    if public_name.blank?
      self.public_name = ""
      self.public_name = "#{first_name} #{last_name}" if !first_name.blank? && !last_name.blank?
    end
  end

  def generate_guid
    begin
      guid = SecureRandom.urlsafe_base64
    end while Person.where(:guid => guid).exists?
    self.guid = guid
  end

end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < ApplicationController
  before_filter :verify_organizer
  respond_to :html

  def index
    @people = Person.all
    mails = []
    @people.each do |p|
      if p.registrations.count < 1 and p.confirmed?
        mails << p.email
     end
    end
    respond_to do |format|
      format.html
      format.text { render :text => mails }
    end
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(params[:person])
    flash[:notice] = 'Person was successfully created.' if @person.save
    respond_with @person, :location => admin_people_path
  end

  def show
    @person = Person.find(params[:id])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    flash[:notice] = 'Person was successfully updated' if @person.update_attributes(params[:person])
    respond_with @person, :location => admin_people_path
  end

  def delete

  end
end

app/views/admin/people/_form.html.haml
= semantic_form_for [:admin, @person] do |f|
  = f.inputs "Basic Information" do
    = f.input :first_name, :as => :string
    = f.input :last_name, :as => :string
    = f.input :public_name, :as => :string
    = f.input :email
    = f.input :company, :as => :string
    = f.input :biography, :input_html => {:rows => 10}
  = f.actions do
    = f.action :submit, :button_html => {:class => "btn primary"}

app/views/admin/people/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        People
        - if @people
          = "(#{@people.length})"
        = link_to "New person", new_admin_person_path, :class => "btn btn-success pull-right"

.row
  .col-md-12
    .well
      %table.table.table-striped.table-bordered.table-hover#people
        %thead
          %th
            %b Email
          %th
            %b Last Name
          %th
            %b First Name
          %th
            %b Public Name
          %th
            %b # of Conference Registrations
          %th
          %th
        - @people.each do |person|
          %tr
            %td= person.email
            %td= person.last_name
            %td= person.first_name
            %td= person.public_name
            %td= person.registrations.count
            %td= link_to "Edit", edit_admin_person_path(person)
            %td= link_to "View", admin_person_path(person)

:javascript
  $(document).ready(function() {
      $('#people').dataTable( {
        "bPaginate": false,
        "bLengthChange": false
      } );
  } );

app/views/admin/people/show.html.haml
%table.table
  %tr
    %td
      %b First Name
    %td
      = @person.first_name
  %tr
    %td
      %b Last Name
    %td
      = @person.last_name
  %tr
    %td
      %b Public Name
    %td
      = @person.public_name
  %tr
    %td
      %b Company
    %td
      = @person.company
  %tr
    %td
      %b Email
    %td
      = @person.email
  %tr
    %td
      %b Created At
    %td
      = @person.created_at
  %tr
    %td
      %b Updated At
    %td
      = @person.updated_at
  %tr
    %td
      %b Biography
    %td
      = @person.biography
  %tr
    %td
      %b Registered to attend
    %td
      - if @person.registrations.count == 0
        None
      - else
        = @person.registrations.map { |r| r.conference.title }.join ','